controller_list:
  - name: fake_drone_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
initial:  # Define initial robot poses per group
#  - group: drone
#    pose: home

  []